name: build_runner_issue
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  path: ^1.4.1
  build: any

dev_dependencies:
  test: ^1.0.0
  build_runner: ^0.9.1
